/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.testmakegui.creategui1;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author dani
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comboBoxBing = new javax.swing.JComboBox<>();
        comboBoxCT = new javax.swing.JComboBox<>();
        comboBoxDaspro = new javax.swing.JComboBox<>();
        comboBoxPDaspro = new javax.swing.JComboBox<>();
        comboBoxMat1 = new javax.swing.JComboBox<>();
        comboBoxPancasila = new javax.swing.JComboBox<>();
        comboBoxKTI = new javax.swing.JComboBox<>();
        ComboBoxK3 = new javax.swing.JComboBox<>();
        ketBing = new javax.swing.JTextField();
        ketCT = new javax.swing.JTextField();
        ketDaspro = new javax.swing.JTextField();
        ketPDaspro = new javax.swing.JTextField();
        ketMat1 = new javax.swing.JTextField();
        ketKTI = new javax.swing.JTextField();
        ketPancasila = new javax.swing.JTextField();
        ketK3 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Check Nilai Mahasiswa");

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Fira Code", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHECK INDEKS PRESTASI MAHASISWA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bahasa Inggris");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Critical Thinking");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dasar Pemrograman");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Praktikum Dasar Pemrograman");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Matematika 1");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pancasila");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Konsep TI");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Keselamatan dan Kesehatan Kerja");

        comboBoxBing.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxBing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBingActionPerformed(evt);
            }
        });

        comboBoxCT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCTActionPerformed(evt);
            }
        });

        comboBoxDaspro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxDaspro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDasproActionPerformed(evt);
            }
        });

        comboBoxPDaspro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxPDaspro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPDasproActionPerformed(evt);
            }
        });

        comboBoxMat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxMat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMat1ActionPerformed(evt);
            }
        });

        comboBoxPancasila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxPancasila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxPancasilaActionPerformed(evt);
            }
        });

        comboBoxKTI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        comboBoxKTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxKTIActionPerformed(evt);
            }
        });

        ComboBoxK3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B+", "B", "C+", "C", "D", "E" }));
        ComboBoxK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxK3ActionPerformed(evt);
            }
        });

        ketBing.setText("Keterangan");
        ketBing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketBingActionPerformed(evt);
            }
        });

        ketCT.setText("Keterangan");
        ketCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketCTActionPerformed(evt);
            }
        });

        ketDaspro.setText("Keterangan");
        ketDaspro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketDasproActionPerformed(evt);
            }
        });

        ketPDaspro.setText("Keterangan");
        ketPDaspro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketPDasproActionPerformed(evt);
            }
        });

        ketMat1.setText("Keterangan");
        ketMat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketMat1ActionPerformed(evt);
            }
        });

        ketKTI.setText("Keterangan");
        ketKTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketKTIActionPerformed(evt);
            }
        });

        ketPancasila.setText("Keterangan");
        ketPancasila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketPancasilaActionPerformed(evt);
            }
        });

        ketK3.setText("Keterangan");
        ketK3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketK3ActionPerformed(evt);
            }
        });

        submit.setText("CHECK IP");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxKTI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketKTI, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketCT, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxBing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketBing, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxPDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketPDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxMat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboBoxPancasila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketPancasila, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ComboBoxK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ketK3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboBoxBing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ketBing, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketCT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ketDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketPDaspro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxMat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketMat1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxPancasila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketPancasila, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxKTI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketKTI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ComboBoxK3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ketK3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ketBingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketBingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketBingActionPerformed

    private void ketCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketCTActionPerformed

    private void ketDasproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketDasproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketDasproActionPerformed

    private void ketPDasproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketPDasproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketPDasproActionPerformed

    private void ketMat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketMat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketMat1ActionPerformed

    private void ketKTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketKTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketKTIActionPerformed

    private void ketPancasilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketPancasilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketPancasilaActionPerformed

    private void ketK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketK3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketK3ActionPerformed
    
    protected double nilai[] = new double[8];
    
    protected void comboBoxKet(JTextField ket, JComboBox comboBox, int index) {
        double IP = 0;
        switch (comboBox.getSelectedIndex()) {
            case 0:
                ket.setText("Sangat Memuaskan");
                IP = 4;
                break;
            case 1:
                ket.setText("Sangat Cukup");
                IP = 3.5;
                break;
            case 2:
                ket.setText("Cukup Memuaskan");
                IP = 3;
                break;
            case 3:
                ket.setText("Cukup");
                IP = 2.5;
                break;
            case 4:
                ket.setText("Kurang");
                IP = 2;
                break;
            case 5:
                ket.setText("Sangat Kurang");
                IP = 1;
                break;
            case 6:
                ket.setText("Kurang Sekali");
                IP = 0;
                break;
        }
        nilai[index] = IP;
    }
    
    private void comboBoxBingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBingActionPerformed
        comboBoxKet(ketBing, comboBoxBing, 0);
    }//GEN-LAST:event_comboBoxBingActionPerformed

    private void comboBoxCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCTActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketCT, comboBoxCT, 1);
    }//GEN-LAST:event_comboBoxCTActionPerformed

    private void comboBoxDasproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxDasproActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketDaspro, comboBoxDaspro, 2);
    }//GEN-LAST:event_comboBoxDasproActionPerformed

    private void comboBoxPDasproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPDasproActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketPDaspro, comboBoxPDaspro, 3);
    }//GEN-LAST:event_comboBoxPDasproActionPerformed

    private void comboBoxMat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxMat1ActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketMat1, comboBoxMat1, 4);
    }//GEN-LAST:event_comboBoxMat1ActionPerformed

    private void comboBoxPancasilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxPancasilaActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketPancasila, comboBoxPancasila, 5);
    }//GEN-LAST:event_comboBoxPancasilaActionPerformed

    private void comboBoxKTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxKTIActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketKTI, comboBoxKTI, 6);
    }//GEN-LAST:event_comboBoxKTIActionPerformed

    private void ComboBoxK3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxK3ActionPerformed
        // TODO add your handling code here:
        comboBoxKet(ketK3, ComboBoxK3, 7);
    }//GEN-LAST:event_ComboBoxK3ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        double total = 0;
        for (double i : nilai) {
            total += i;
        }
        
        total /= nilai.length;
       
       JOptionPane.showMessageDialog(this, "Hasil IP total adalah : " + total);
    }//GEN-LAST:event_submitActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxK3;
    private javax.swing.JComboBox<String> comboBoxBing;
    private javax.swing.JComboBox<String> comboBoxCT;
    private javax.swing.JComboBox<String> comboBoxDaspro;
    private javax.swing.JComboBox<String> comboBoxKTI;
    private javax.swing.JComboBox<String> comboBoxMat1;
    private javax.swing.JComboBox<String> comboBoxPDaspro;
    private javax.swing.JComboBox<String> comboBoxPancasila;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField ketBing;
    private javax.swing.JTextField ketCT;
    private javax.swing.JTextField ketDaspro;
    private javax.swing.JTextField ketK3;
    private javax.swing.JTextField ketKTI;
    private javax.swing.JTextField ketMat1;
    private javax.swing.JTextField ketPDaspro;
    private javax.swing.JTextField ketPancasila;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
